[en_US]
v = "Try another password that contains at least:"

[es_ES]
v = "Pruebe otra contraseña que contenga al menos:"

[ru_RU]
v = "Попробуйте другой пароль, который содержит как минимум:"

[fr_FR]
v = "Utilise un autre mot de passe qui contient au moins :"

[vi_VN]
v = "Thử một mật khẩu khác có các yêu cầu tối thiểu sau:"
