[en_US]
v = "No leading or trailing whitespace"

[es_ES]
v = "Sin espacios al inicio ni al final"

[fr_FR]
v = "Pas de caractères blancs au début ou à la fin"

[ru_RU]
v = "Без пробелов в начале или в конце"
