[en_US]
v = "Incorrect passphrase or invalid file"

[es_ES]
v = "Frase de contraseña incorrecta o archivo inválido"

[fr_FR]
v = "Phrase de passe incorrecte ou fichier invalide"

[ru_RU]
v = "Неверная парольная фраза или недопустимый файл"
