[en_US]
v = "1 special character e.g., $, !, @, %, &"

[es_ES]
v = "1 carácter especial p. ej., $, !, @, %, &"

[fr_FR]
v = "1 caractère spécial ex. $, !, @, %, &"

[ru_RU]
v = "1 специальный символ, например $, !, @, %, &"
