[en_US]
v = "Incorrect passphrase/password or invalid file"

[es_ES]
v = "Contraseña/frase de contraseña incorrecta o archivo no válido"

[ru_RU]
v = "Неверная парольная фраза/пароль или недействительный файл"
