[en_US]
v = "Using biometric unlock may erase your accounts if lock screen or private spaces change, your device updates, or if the app hasn't been opened in a while. Your accounts can be recovered if you enable automatic internal backups."

[es_ES]
v = "El uso del desbloqueo biométrico puede borrar tus cuentas si cambia la pantalla de bloqueo o los espacios privados, si se actualiza tu dispositivo o si la aplicación no se ha abierto durante un tiempo. Tus cuentas se pueden recuperar si habilitas las copias de seguridad internas automáticas."

[ru_RU]
v = "Использование биометрической разблокировки может привести к удалению ваших аккаунтов, если изменится экран блокировки или личные пространства, обновится ваше устройство или если приложение не открывалось в течение некоторого времени. Ваши аккаунты можно восстановить, если включить автоматические внутренние резервные копии."
