[en_US]
v = "Incorrect password or invalid file"

[es_ES]
v = "Contraseña incorrecta o archivo no válido"

[fr_FR]
v = "Mot de passe incorrect ou fichier invalide"

[ru_RU]
v = "Неверный пароль или недопустимый файл"
