[en_US]
v = "You're using an advanced feature. Automatic internal backups are highly recommended."

[es_ES]
v = "Estás utilizando una función avanzada. Te recomendamos que actives las copias de seguridad internas automáticas."

[ru_RU]
v = "Вы используете расширенную функцию. Настоятельно рекомендуется включить автоматические внутренние резервные копии."
