[en_US]
v = "Automatic Internal Backups"

[es_ES]
v = "Copias de Seguridad Internas Automáticas"

[fr_FR]
v = "Sauvegardes internes automatiques"

[ru_RU]
v = "Автоматические Внутренние Резервные Копии"
