[en_US]
one = "Tap %d more time to delete account"
other = "Tap %d more times to delete account"

[es_ES]
one = "Pulsa %d vez más para eliminar la cuenta"
other = "Pulsa %d veces más para eliminar la cuenta"

[ru_RU]
one = "Нажмите ещё %d раз, чтобы удалить аккаунт"
few = "Нажмите ещё %d раза, чтобы удалить аккаунт"
many = "Нажмите ещё %d раз, чтобы удалить аккаунт"
other = "Нажмите ещё %d раза, чтобы удалить аккаунт"
