[en_US]
one = "Tap %d more time to wipe and start over"
other = "Tap %d more times to wipe and start over"

[es_ES]
one = "Pulsa %d vez más para borrar y empezar de nuevo."
other = "Pulsa %d veces más para borrar y empezar de nuevo."

[ru_RU]
one = "Нажмите ещё %d раз, чтобы сбросить и начать заново"
few = "Нажмите ещё %d раза, чтобы сбросить и начать заново"
many = "Нажмите ещё %d раз, чтобы сбросить и начать заново"
other = "Нажмите ещё %d раза, чтобы сбросить и начать заново"
