[en_US]
v = "Unable to load decryption keys. For more information, see the app log."

[es_ES]
v = "No se pueden cargar las claves de descifrado. Para obtener más información, consulte el registro de la aplicación."

[ru_RU]
v = "Не удалось загрузить ключи расшифровки. Для получения подробной информации смотрите журнал приложения."
