[en_US]
v = "Unable to load decryption keys. For more information, see the app log."

[es_ES]
v = "No se pudieron cargar las claves de descifrado. Para más información, consulta el registro de la app."

[fr_FR]
v = ""

[ru_RU]
v = "Не удалось загрузить ключи расшифровки. Для получения подробной информации смотрите журнал приложения."
