[en_US]
v = "An internal backup was found. If you wipe and start over, you'll be able to recover your accounts as long as you remember the passphrase/password."

[es_ES]
v = "Se ha encontrado una copia de seguridad interna. Si borras y empiezas de nuevo, podrás recuperar tus cuentas siempre y cuando recuerdes la contraseña o frase de contraseña."

[ru_RU]
v = "Была найдена внутренняя резервная копия. Если вы удалите все данные и начнете заново, вы сможете восстановить свои аккаунты, если помните пароль/парольную фразу."
