[en_US]
v = "An internal backup was found. If you wipe and start over, you'll be able to recover your accounts as long as you remember the passphrase."

[es_ES]
v = "Se encontró una copia interna. Si borras y comienzas de nuevo, podrás recuperar tus cuentas siempre que recuerdes la frase de contraseña."

[fr_FR]
v = "Une sauvegarde interne a été trouvée. Si vous réinitialisez et recommencez, vous pourrez récupérer vos comptes tant que vous vous rappelez de la phrase de passe."

[ru_RU]
v = "Найдена внутренняя резервная копия. Если вы выполните сброс и начнёте заново, вы сможете восстановить свои аккаунты, если вспомните парольную фразу."
