[en_US]
v = "An internal backup was found. Now is the time to recover your accounts."

[es_ES]
v = "Se ha encontrado una copia de seguridad interna. Ahora es el momento de recuperar sus cuentas."

[ru_RU]
v = "Найдена внутренняя резервная копия. Сейчас подходящее время для восстановления ваших аккаунтов."
