[en_US]
v = "979 needs your support to continue"

[es_ES]
v = "979 necesita tu apoyo para continuar"

[fr_FR]
v = "979 a besoin de votre soutien pour continuer"

[ru_RU]
v = "979 нуждается в вашей поддержке, чтобы продолжать"
