[en_US]
v = "Block screenshots and recordings"

[es_ES]
v = "Bloquear capturas de pantalla y grabaciones"

[fr_FR]
v = "Bloquer les captures d'écran et les enregistrements"

[ru_RU]
v = "Блокировать скриншоты и записи"
